# Generated by Django 4.2.30 on 2026-07-29 21:23

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ عضویت (شمسی)'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('ordinary', 'کاربر عادی'), ('ceo', 'مدیر عامل'), ('inspector', 'بازرس'), ('other', 'سایر')], default='ordinary', max_length=20, verbose_name='نقش در انجمن'),
        ),
    ]
