# Generated by Django 4.2.30 on 2026-07-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_works', to='member.member', verbose_name='عضو مجری'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
