# Generated by Django 4.2.30 on 2026-07-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_member_membership_date_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=120, verbose_name='متن بالای عنوان (Eyebrow)')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='عنوان اصلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='تصویر پس\u200cزمینه')),
                ('cta_text', models.CharField(blank=True, max_length=80, verbose_name='متن دکمه')),
                ('cta_url', models.CharField(blank=True, help_text='مثال: /members/ یا https://example.com', max_length=300, verbose_name='لینک دکمه')),
                ('cta2_text', models.CharField(blank=True, max_length=80, verbose_name='متن دکمه دوم')),
                ('cta2_url', models.CharField(blank=True, max_length=300, verbose_name='لینک دکمه دوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
