# Generated by Django 4.2.30 on 2026-07-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_completedwork_member_delete_member_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSlide',
        ),
    ]
