# Generated by Django 4.2.30 on 2026-07-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_jalali_dates_role_heroslide'),
        ('portal', '0003_slider'),
    ]

    operations = [
    ]
