# Generated by Django 4.2.30 on 2026-07-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان زمینه\u200cی فعالیت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=170, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'زمینه\u200cی فعالیت',
                'verbose_name_plural': 'زمینه\u200cهای فعالیت',
                'ordering': ['title'],
            },
        ),
    ]
