# Generated by Django 4.2.30 on 2026-07-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='HeroSlide',
        ),
    ]
